binop_separator = "Back"
blank_lines_lower_bound = 0
brace_style = "SameLineWhere"
combine_control_expr = true
comment_width = 80
condense_wildcard_suffixes = true
control_brace_style = "AlwaysSameLine"
doc_comment_code_block_width = 80
empty_item_single_line = true
format_code_in_doc_comments = true
format_strings = true
group_imports = "StdExternalCrate"
hex_literal_case = "Upper"
imports_granularity = "Crate"
imports_indent = "Block"
imports_layout = "Mixed"
indent_style = "Block"
match_arm_blocks = true
match_block_trailing_comma = true
merge_derives = true
normalize_comments = true
normalize_doc_attributes = true
remove_nested_parens = true
reorder_impl_items = true
reorder_imports = true
reorder_modules = true
space_after_colon = true
space_before_colon = false
trailing_comma = "Vertical"
trailing_semicolon = true
type_punctuation_density = "Wide"
use_try_shorthand = true
wrap_comments = true
